# Generated by Django 5.2.8 on 2025-11-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=255),
        ),
    ]
